{{- if .Values.apps.mysql.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.mysql.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  serviceName: {{ .Values.mysql.name }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.mysql.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.mysql.name }}
    spec:
      containers:
      - name: {{ .Values.mysql.name }}
        image: {{ .Values.mysql.image }}
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: springboot-secrets
              key: DB_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: springboot-secrets
              key: DB_NAME
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: springboot-secrets
              key: DB_PASSWORD
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: springboot-secrets
              key: DB_USERNAME
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
        ports:
        - containerPort: {{ .Values.mysql.port }}
        resources:
          requests:
            cpu: {{ .Values.mysql.resources.requests.cpu }}
            memory: {{ .Values.mysql.resources.requests.memory }}
          limits:
            cpu: {{ .Values.mysql.resources.limits.cpu }}
            memory: {{ .Values.mysql.resources.limits.memory }}
  volumeClaimTemplates:
  - metadata:
      name: mysql-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: {{ .Values.mysql.storage.storageClass }}
      resources:
        requests:
          storage: {{ .Values.mysql.storage.size }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysql.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  ports:
    - port: {{ .Values.mysql.port }}
      name: mysql
  selector:
    app: {{ .Values.mysql.name }}
  type: ClusterIP
{{- end }}