# external-secret-springboot-dev.yaml
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: springboot-secrets
  namespace: hertz-tuning-dev
spec:
  refreshInterval: 3m
  secretStoreRef:
    name: aws-ssm-store
    kind: ClusterSecretStore
  target:
    name: springboot-secrets
    creationPolicy: Owner
  dataFrom:
    - find:
        path: /global/springboot/dev
        name:
          regexp: ".*"
      rewrite:
        - regexp:
            source: "/global/springboot/dev/(.*)"
            target: "$1"
