apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "nextjs-fe.fullname" . }}-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/enable-websocket: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          # 1) Next.js 정적 _next/
          - path: /_next
            pathType: Prefix
            backend:
              service:
                name: {{ include "nextjs-fe.fullname" . }}-svc
                port:
                  number: 80

          # 2) API 요청 → Spring Boot 서비스
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "springboot-be.fullname" . }}-svc
                port:
                  number: 80

          # 3) WebSocket 요청 → Spring Boot WebSocket 엔드포인트
          - path: /ws
            pathType: Prefix
            backend:
              service:
                name: {{ include "springboot-be.fullname" . }}-svc
                port:
                  number: 80

          # 4) 나머지 모든 경로 → Next.js
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "nextjs-fe.fullname" . }}-svc
                port:
                  number: 80