apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "nextjs-fe.fullname" . }}-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /_next
            pathType: Prefix
            backend:
              service:
                name: {{ include "nextjs-fe.fullname" . }}-svc
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "nextjs-fe.fullname" . }}-svc
                port:
                  number: 80