apiVersion: v1
kind: Service
metadata:
  name: {{ include "nextjs-fe.fullname" . }}-svc
spec:
  type: ClusterIP
  selector:
    app: nextjs-fe
  ports:
    - name: http
      port: 80
      targetPort: 3000