{{- if .Values.global.createClusterSecretStore }}
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-ssm-store
spec:
  provider:
    aws:
      service: ParameterStore
      region: ap-northeast-2
      auth:
        secretRef:
          accessKeyID:
            name: {{ .Values.global.awsSecretName }}
            key: access-key-id
            namespace: {{ .Values.global.secretNamespace }}
          secretAccessKey:
            name: {{ .Values.global.awsSecretName }}
            key: secret-access-key
            namespace: {{ .Values.global.secretNamespace }}
{{- end }}