version: '3.8'

services:
  tuning-api:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/tuning-api:${IMAGE_TAG:-latest}
    container_name: fastapi-ai-server
    restart: always
    ports:
      - "8000:8000"
    cap_add:
      - SYS_PTRACE
    environment:
      - UVICORN_WORKERS=2
      - CHROMA_HOST=chromadb
      - CHROMA_PORT=8001
      - CHROMA_MODE=server
      - TOKENIZERS_PARALLELISM=false
    volumes:
      - tuning_logs:/app/logs
    depends_on:
      - chromadb
    deploy:
      resources:
        limits:
          cpus: "3.0"
          memory: "11G"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health/chromadb"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 60s
    networks:
      - app_network

  chromadb:
    image: ghcr.io/chroma-core/chroma:0.4.13  # 또는 :latest
    container_name: chromadb
    restart: always
    expose:
      - "8001"
    cap_add:
      - SYS_PTRACE
    volumes:
      - chroma_data:/chroma/chroma
    environment:
      - ALLOW_RESET=true
      - ANONYMIZED_TELEMETRY=false
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8001
    deploy:
      resources:
        limits:
          cpus: "0.8"
          memory: "4.5G"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/api/v2/heartbeat"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_network

volumes:
  tuning_logs:
  chroma_data:

networks:
  app_network:
    driver: bridge