apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hertz-tuning-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: hertz-tuning
  source:
    repoURL: https://github.com/YOUR_USERNAME/ktb-final-project.git  # 실제 Git 저장소 URL로 변경
    targetRevision: HEAD
    path: 2-hertz-cloud/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: hertz-tuning-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
  revisionHistoryLimit: 10