apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "springboot-be.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 3m
  secretStoreRef:
    name: aws-ssm-store
    kind: ClusterSecretStore
  target:
    name: {{ include "springboot-be.fullname" . }}-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ .Values.secret.path }}