apiVersion: v1
kind: Service
metadata:
  name: {{ include "springboot-be.fullname" . }}-svc
spec:
  type: ClusterIP
  selector:
    app: {{ include "springboot-be.fullname" . }}
  ports:
    - name: http
      port: 80
      targetPort: 8080