# Global settings
global:
  namespace: hertz-tuning-dev
  region: ap-northeast-2
  accountId: "969400486509"
  environment: dev

# Image settings
image:
  repository: 969400486509.dkr.ecr.ap-northeast-2.amazonaws.com/tuning-springboot
  tag: k8s-develop-latest

# Service Account
serviceAccount:
  ecrAccess: ecr-access-sa

# Application settings
app:
  name: springboot-be
  ports:
    http: 8080
    websocket: 9100

# Resources
resources:
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: 1
    memory: 1Gi

# HPA settings
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPU: 70
  targetMemory: 80
  scaleUp:
    stabilizationWindowSeconds: 60
    percent: 100
    periodSeconds: 15
  scaleDown:
    stabilizationWindowSeconds: 300
    percent: 10
    periodSeconds: 60

# Observability
observability:
  signoz:
    # endpoint: "http://signoz-otel-collector.observability.svc.cluster.local:4318"
    endpoint: "http://cloud.hertz-tuning.com:4317"