apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  namespace: argocd
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: argocd
    meta.helm.sh/release-namespace: argocd
    argocd.argoproj.io/sync-wave: "3"
    argocd-image-updater.argoproj.io/image-list: frontend=969400486509.dkr.ecr.ap-northeast-2.amazonaws.com/tuning-nextjs
    argocd-image-updater.argoproj.io/frontend.update-strategy: latest
    argocd-image-updater.argoproj.io/frontend.allow-tags: regexp:^k8s-develop-.*$
spec:
  project: tuning-dev
  source:
    repoURL: https://github.com/100-hours-a-week/2-hertz-cloud.git
    targetRevision: {{ .Values.applications.git.targetRevision }}
    path: k8s-argocd-helm/apps/frontend
  destination:
    server: https://kubernetes.default.svc
    namespace: hertz-tuning-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
