apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
  namespace: argocd
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: argocd
    meta.helm.sh/release-namespace: argocd
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: tuning-dev
  source:
    repoURL: https://github.com/100-hours-a-week/2-hertz-cloud.git
    targetRevision: {{ .Values.applications.git.targetRevision }}
    path: k8s-argocd-helm/apps/kafka
  destination:
    server: https://kubernetes.default.svc
    namespace: hertz-tuning-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true