# springboot-backend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-be
  namespace: hertz-tuning-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-be
  template:
    metadata:
      labels:
        app: springboot-be
    spec:
      serviceAccountName: ecr-access-sa  # IRSA Service Account 사용
      containers:
        - name: springboot-be
          image: 969400486509.dkr.ecr.ap-northeast-2.amazonaws.com/tuning-springboot:prod-latest
          #args: ["--spring.mvc.async.request-timeout=-1"]
          envFrom:
            - secretRef:
                name: springboot-secrets
          env:
            - name: DB_HOST
              value: mysql   # DB_HOST만 고정
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30

          readinessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 1
              memory: 1Gi
---
# springboot-backend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: springboot-be-svc      # 서비스 이름도 통일
  namespace: hertz-tuning-dev
spec:
  type: ClusterIP
  selector:
    app: springboot-be
  ports:
    - name: http
      port: 80
      targetPort: 8080
