{{- if .Values.apps.kafka.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  namespace: {{ .Values.global.namespace }}
data:
  ZOOKEEPER_CLIENT_PORT: "{{ .Values.kafka.zookeeper.port }}"
  ZOOKEEPER_TICK_TIME: "2000"
  KAFKA_ZOOKEEPER_CONNECT: "zookeeper:{{ .Values.kafka.zookeeper.port }}"
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
  KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "{{ .Values.kafka.replicas }}"
{{- end }}