apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-crds
  namespace: {{ .Values.global.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: tuning-{{ .Values.global.environment }}
  source:
    repoURL: https://github.com/prometheus-operator/prometheus-operator
    targetRevision: v0.68.0
    path: example/prometheus-operator-crd
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true