apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: {{ .Values.global.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: tuning-{{ .Values.global.environment }}
  source:
    repoURL: {{ .Values.prometheus.chart.repository }}
    chart: {{ .Values.prometheus.chart.name }}
    targetRevision: {{ .Values.prometheus.chart.version }}
    helm:
      releaseName: prometheus-stack
      skipCrds: true
      values: |
{{ .Values.prometheus.config | toYaml | indent 8 }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.global.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
  - group: ""
    kind: PersistentVolumeClaim
    jsonPointers:
    - /spec/volumeName
