apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-crd-installer
  namespace: {{ .Values.global.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-crd-installer
  annotations:
    argocd.argoproj.io/sync-wave: "0"
rules:
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-crd-installer
  annotations:
    argocd.argoproj.io/sync-wave: "0"
subjects:
- kind: ServiceAccount
  name: prometheus-crd-installer
  namespace: {{ .Values.global.namespace }}
roleRef:
  kind: ClusterRole
  name: prometheus-crd-installer
  apiGroup: rbac.authorization.k8s.io