# Global settings
global:
  namespace: hertz-tuning-dev
  environment: dev

# SigNoz Chart Values (경량화 + k8s-infra)
signoz:
  # ClickHouse (로그 + 메트릭 저장소)
  clickhouse:
    enabled: true
    installCustomStorageClass: false
    persistence:
      enabled: true
      storageClass: mysql-ebs
      size: 4Gi
    resources:
      requests:
        memory: "512Mi"
        cpu: "200m"
      limits:
        memory: "1Gi"
        cpu: "400m"
    layout:
      shardsCount: 1
      replicasCount: 1
  
  # 불필요한 컴포넌트 비활성화
  zookeeper:
    enabled: false
  kafka:
    enabled: false
  alertmanager:
    enabled: false
  
  # Query Service
  queryService:
    enabled: true
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "200m"
  
  # Frontend
  frontend:
    enabled: true
    resources:
      requests:
        memory: "128Mi"
        cpu: "50m"
      limits:
        memory: "256Mi"
        cpu: "100m"
  
  # OTel Collector
  otelCollector:
    enabled: true
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "200m"
  
  # 메트릭 수집기 비활성화 (k8s-infra가 대신 처리)
  otelCollectorMetrics:
    enabled: false
  
  # 로그 수집만 활성화
  presets:
    logsCollection:
      enabled: true
      includeNamespaces: 
        - hertz-tuning-dev
    # 다른 메트릭들은 k8s-infra가 처리
    kubeletMetrics:
      enabled: false
    hostMetrics:
      enabled: false
    clusterMetrics:
      enabled: false
    kubernetesEvents:
      enabled: false
  
  global:
    storageClass: mysql-ebs
    cloud: others
    clusterName: hertz-tuning-dev
    deploymentEnvironment: dev

# k8s-infra Chart Values (CPU/Memory 메트릭 전용)
k8sInfra:
  enabled: true
  
  # OTel Collector for Infrastructure Metrics
  otelCollector:
    resources:
      requests:
        memory: "128Mi"
        cpu: "50m"
      limits:
        memory: "256Mi"
        cpu: "100m"
  
  # OTel Agent (각 노드에서 메트릭 수집)
  otelAgent:
    resources:
      requests:
        memory: "64Mi"
        cpu: "25m"
      limits:
        memory: "128Mi"
        cpu: "50m"
  
  # 수집할 메트릭 설정
  presets:
    # Kubelet 메트릭 (Pod CPU/Memory)
    kubeletMetrics:
      enabled: true
    # 호스트 메트릭 (Node CPU/Memory)
    hostMetrics:
      enabled: true
    # 클러스터 메트릭
    clusterMetrics:
      enabled: false
    # Kubernetes 이벤트
    kubernetesEvents:
      enabled: false