# SigNoz Chart Values (경량화 + k8s-infra)
signoz:
  # ClickHouse (로그 + 메트릭 저장소)
  clickhouse:
    enabled: true
    installCustomStorageClass: false
    persistence:
      enabled: true
      storageClass: mysql-ebs
      size: 4Gi
    resources:
      requests:
        memory: "2Gi"
        cpu: "500m"
      limits:
        memory: "4Gi"
        cpu: "1"
    layout:
      shardsCount: 1
      replicasCount: 1

  # 불필요한 컴포넌트 비활성화
  zookeeper:
    enabled: false
  kafka:
    enabled: false
  alertmanager:
    enabled: false

  # Query Service
  queryService:
    enabled: true
    resources:
      requests:
        memory: "1Gi"
        cpu: "250m"
      limits:
        memory: "2Gi"
        cpu: "500m"

  # Frontend
  frontend:
    enabled: true
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "200m"

  # OTel Collector
  otelCollector:
    enabled: true
    resources:
      requests:
        memory: "512Mi"
        cpu: "200m"
      limits:
        memory: "1Gi"
        cpu: "400m"

  # 애플리케이션 메트릭 수집기 (SpringBoot, MySQL 성능)
  otelCollectorMetrics:
    enabled: true
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "200m"

  # 로그 수집만 활성화
  presets:
    logsCollection:
      enabled: true
      includeNamespaces:
        - hertz-tuning-stage
    # 다른 메트릭들은 k8s-infra가 처리
    clusterMetrics:
      enabled: false
    kubernetesEvents:
      enabled: false
    kubeletMetrics:
      enabled: true
    hostMetrics:
      enabled: true

  global:
    namespace: observability
    storageClass: mysql-ebs
    cloud: others
    clusterName: hertz-tuning-stage
    deploymentEnvironment: stage