# Global settings
global:
  namespace: hertz-tuning-dev
  environment: dev

# SigNoz settings
signoz:
  namespace: observability
  storageClass: mysql-ebs
  clickhouse:
    storage:
      size: 12Gi
    resources:
      requests:
        memory: "4Gi"
        cpu: "1000m"
      limits:
        memory: "8Gi"
        cpu: "2000m"
  zookeeper:
    storage:
      size: 6Gi
    resources:
      requests:
        memory: "2Gi"
        cpu: "500m"
      limits:
        memory: "4Gi"
        cpu: "1000m"
  kafka:
    storage:
      size: 6Gi