# Global settings
global:
  namespace: hertz-tuning-dev
  environment: dev

# SigNoz Chart Values (경량화)
signoz:
  global:
    storageClass: mysql-ebs
    cloud: others
    clusterName: hertz-tuning-dev
    deploymentEnvironment: dev
  
  clickhouse:
    installCustomStorageClass: false
    persistence:
      enabled: true
      storageClass: mysql-ebs
      size: 8Gi
    resources:
      requests:
        memory: "1Gi"
        cpu: "500m"
      limits:
        memory: "2Gi"
        cpu: "1000m"
  
  zookeeper:
    persistence:
      enabled: true
      storageClass: mysql-ebs
      size: 4Gi
    resources:
      requests:
        memory: "512Mi"
        cpu: "250m"
      limits:
        memory: "1Gi"
        cpu: "500m"
  
  kafka:
    persistence:
      enabled: true
      storageClass: mysql-ebs
      size: 4Gi
    resources:
      requests:
        memory: "512Mi"
        cpu: "250m"
      limits:
        memory: "1Gi"
        cpu: "500m"
  
  otelCollectorEndpoint: signoz-otel-collector.observability.svc.cluster.local:4317
  otelInsecure: true
  
  presets:
    hostMetrics:
      enabled: false
    kubeletMetrics:
      enabled: false
    clusterMetrics:
      enabled: false
    logsCollection:
      enabled: false