name: Test Discord Notification

on:
  workflow_dispatch:

jobs:
  test-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send test message to Discord
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{
                 "content": "✅ 테스트 메시지입니다. PR 알림 포맷을 확인 중입니다.\n\n**Title:** Test PR\n**Author:** tester\n\n📝 **Description:**\nThis is a test run.\n\n🔗 https://github.com/example/repo/pull/1"
               }' \
               "${{ secrets.DISCORD_WEBHOOK_URL }}"
