apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.global.namespace }}
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.ecrAccess }}
      containers:
        - name: {{ .Values.app.name }}
          image: {{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
          envFrom:
            - secretRef:
                name: springboot-secrets
          env:
            - name: OTEL_SERVICE_NAME
              value: "{{ .Values.app.name }}"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "{{ .Values.observability.signoz.endpoint }}"
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: "http/protobuf"
            - name: OTEL_LOGS_EXPORTER
              value: "otlp"
            - name: OTEL_METRICS_EXPORTER
              value: "otlp"
            - name: OTEL_TRACES_EXPORTER
              value: "otlp"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.name={{ .Values.app.name }},service.version={{ .Values.image.tag }},deployment.environment={{ .Values.global.environment }}"
            - name: LOGGING_LEVEL_ROOT
              value: "INFO"
            - name: LOGGING_PATTERN_CONSOLE
              value: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
          ports:
            - containerPort: {{ .Values.app.ports.http }}
            - containerPort: {{ .Values.app.ports.websocket }}
          readinessProbe:
            httpGet:
              path: /api/ping
              port: {{ .Values.app.ports.http }}
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /api/ping
              port: {{ .Values.app.ports.http }}
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}