apiVersion: v2
name: monitoring
description: Monitoring Stack with Prometheus, Grafana, Loki
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: kube-prometheus-stack
    version: "58.2.0"
    repository: https://prometheus-community.github.io/helm-charts
  - name: loki
    version: "5.41.4"
    repository: https://grafana.github.io/helm-charts
  - name: promtail
    version: "6.15.3"
    repository: https://grafana.github.io/helm-charts
keywords:
  - monitoring
  - prometheus
  - grafana
  - loki
maintainers:
  - name: hertz-team