apiVersion: v1
kind: Namespace
metadata:
  name: hertz-tuning-prod
  labels:
    name: hertz-tuning-prod
    environment: prod
    project: hertz-tuning
  annotations:
    description: "Hertz Tuning Production Environment"