# .github/workflows/fastapi-ai-ci.yml

name: AI CI

on:
  pull_request:
    types: [closed]
    branches: 
#     - develop
#     - main
     - feature/ai
jobs:
  ai-ci:
    runs-on: ubuntu-latest

    steps:
    # 1. 소스 코드 체크아웃
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 1

    # 2. Python 3.10 설치 및 캐시 설정
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
        cache-dependency-path: |
          requirements.txt
          requirements-dev.txt

    # 3. 가상환경 생성 및 활성화
    - name: Create and activate virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate

    # 4. 의존성 설치 (병렬 처리 및 캐시 활용)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # requirements.txt 설치 (없으면 건너뜀)
        pip install -r requirements.txt || echo "📦 requirements.txt 없음, 건너뜀"
        # requirements-dev.txt 설치 (없으면 건너뜀)
        pip install -r requirements-dev.txt || echo "📦 requirements-dev.txt 없음, 건너뜀"
        # 기본 의존성 설치 (한 번에 설치)
        pip install "pydantic[email]" fastapi uvicorn transformers torch pytest pytest-asyncio httpx


    # 5. Discord 알림
    - name: Send success notification
      if: success()
      run: |
        curl -H "Content-Type: application/json" \
             -X POST \
             -d "{\"username\": \"AI CI\", \"content\": \"✅ [AI CI 성공] **${{ github.base_ref }}** AI 서버 (브랜치: \`${{ github.head_ref }}\`)\\n🔖 Commit: ${{ github.sha }}\"}" \
             ${{ secrets.DISCORD_WEBHOOK_URL }}

    - name: Send failure notification
      if: failure()
      run: |
        curl -H "Content-Type: application/json" \
             -X POST \
             -d "{\"username\": \"AI CI\", \"content\": \"❌ [AI CI 실패] **${{ github.base_ref }}** AI 서버 (브랜치: \`${{ github.head_ref }}\`)\\n🔖 Commit: ${{ github.sha }}\\n⚠️ 원인: 워크플로우 실행 중 오류 발생\"}" \
             ${{ secrets.DISCORD_WEBHOOK_URL }}
