name: Notify Discord on PR Merged to Develop

on:
  pull_request:
    types: [closed]  # PR이 닫혔을 때 (병합 포함)
    branches:
      - develop       # develop 브랜치로 PR 병합 시 감지

jobs:
  notify:
    if: github.event.pull_request.merged == true  # 병합된 경우만 실행
    runs-on: ubuntu-latest
    steps:
      - name: Send test message to Discord
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{
                 "content": "✅ 테스트 메시지입니다. PR 알림 포맷을 확인 중입니다.\n\n**Title:** Test PR\n**Author:** tester\n\n📝 **Description:**\nThis is a test run.\n\n🔗 https://github.com/example/repo/pull/1"
               }' \
               "${{ secrets.DISCORD_WEBHOOK_URL }}"