name: Notify Discord on PR Merged to Develop

on:
  pull_request:
    types: [closed]
    branches:
      - develop

jobs:
  notify:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
      BASE_BRANCH: ${{ github.event.pull_request.base.ref }}
      PR_TITLE: ${{ github.event.pull_request.title }}
      PR_AUTHOR: ${{ github.event.pull_request.user.login }}
      PR_URL: ${{ github.event.pull_request.html_url }}
      PR_BODY: ${{ github.event.pull_request.body || '내용 없음' }}
    steps:
      - name: Send Discord notification (embed)
        run: |
          # 본문 이스케이프
          PR_BODY_ESCAPED=$(echo "$PR_BODY" | jq -Rs . | sed 's/^"//;s/"$//')

          curl -H "Content-Type: application/json" \
            -X POST \
            -d "{
              \"embeds\": [
                {
                  \"title\": \"✅ PR Merged to \\`$BASE_BRANCH\\` branch! [PR 링크]\",
                  \"url\": \"$PR_URL\",
                  \"description\": \"**Title:** $PR_TITLE\\n**Author:** $PR_AUTHOR\\n\\n📝 **Description:**\\n\`\`\`\\n$PR_BODY_ESCAPED\\n\`\`\`\",
                  \"color\": 3066993
                }
              ]
            }" "$DISCORD_WEBHOOK_PR_URL"
        env:
          DISCORD_WEBHOOK_PR_URL: ${{ secrets.DISCORD_WEBHOOK_PR_URL }}