name: Notify Discord on PR Merged to Develop

on:
  pull_request:
    types: [closed]  # PR이 닫혔을 때 (병합 포함)
    branches:
      - develop       # develop 브랜치로 PR 병합 시 감지

jobs:
  notify:
    if: github.event.pull_request.merged == true  # 병합된 경우만 실행
    runs-on: ubuntu-latest
    steps:
      - name: Send PR info to Discord
        run: |
            curl -H "Content-Type: application/json" \
                -X POST \
                -d @- "${{ secrets.DISCORD_WEBHOOK_URL }}" <<EOF
            {
            "embeds": [
                {
                "title": "✅ PR Merged to develop!",
                "description": "**Title:** ${{ github.event.pull_request.title }}\\n**Author:** ${{ github.event.pull_request.user.login }}\\n\\n📝 **Description:**\\n${{ github.event.pull_request.body }}",
                "url": "${{ github.event.pull_request.html_url }}",
                "color": 3066993
                }
            ]
            }
            EOF