name: Notify Discord on PR Merged to Develop

on:
  pull_request:
    types: [closed]  # PR이 닫혔을 때 (병합 포함)
    branches:
      - develop       # develop 브랜치로 PR 병합 시 감지

jobs:
  notify:
    if: github.event.pull_request.merged == true  # 병합된 경우만 실행
    runs-on: ubuntu-latest
    steps:
      - name: Dump event payload
        run: echo '${{ toJson(github.event) }}' > event.json
      - name: Send notification to Discord
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_AUTHOR: ${{ github.event.pull_request.user.login }}
          PR_URL: ${{ github.event.pull_request.html_url }}
          PR_BODY: ${{ github.event.pull_request.body || '내용 없음' }}
        run: |
          # PR 본문을 JSON 형식에 맞게 이스케이프 처리
          PR_BODY_ESCAPED=$(echo "$PR_BODY" | jq -Rs .)
          
          # Discord로 메시지 전송
          curl -H "Content-Type: application/json" \
              -X POST \
              -d "{\"content\": \"✅ PR Merged to **develop**!\\n\\n**Title:** $PR_TITLE\\n**Author:** $PR_AUTHOR\\n\\n📝 **Description:**\\n\`\`\`markdown\\n$(echo $PR_BODY_ESCAPED | sed 's/^"//;s/"$//')\\n\`\`\`\\n\\n🔗 $PR_URL\"}" \
              "${{ secrets.DISCORD_WEBHOOK_URL }}"