name: Deploy by ECR Image Tag

on:
  workflow_dispatch:
    inputs:
      service:
        description: 'Service name (backend/frontend)'
        required: true
        type: choice
        options:
          - backend
          - frontend
      image_tag:
        description: 'ECR Image Tag (e.g., k8s-develop-abc1234)'
        required: true
        type: string
      target_branch:
        description: 'Target ArgoCD branch'
        required: false
        default: 'develop'
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Validate image tag
        run: |
          echo "🔍 Validating image tag: ${{ inputs.image_tag }}"
          if [[ ! "${{ inputs.image_tag }}" =~ ^k8s-.+ ]]; then
            echo "❌ Invalid image tag format. Expected: k8s-*"
            exit 1
          fi
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Verify image exists in ECR
        run: |
          echo "🔍 Checking if image exists in ECR..."
          REPOSITORY=tuning-${{ inputs.service == 'backend' && 'springboot' || 'nextjs' }}
          aws ecr describe-images \
            --repository-name $REPOSITORY \
            --image-ids imageTag=${{ inputs.image_tag }} \
            --region ap-northeast-2 || {
            echo "❌ Image not found in ECR: ${{ inputs.image_tag }}"
            exit 1
          }
          echo "✅ Image found in ECR"
          
      - name: Clone cloud repository
        uses: actions/checkout@v3
        with:
          repository: 100-hours-a-week/2-hertz-cloud
          token: ${{ secrets.TOKEN_GIHUB }}
          ref: ${{ inputs.target_branch }}
          path: cloud-repo
          
      - name: Check current image tag
        id: check-tag
        working-directory: cloud-repo
        run: |
          CURRENT_TAG=$(grep "tag:" k8s-argocd-helm/apps/${{ inputs.service }}/values.yaml | awk '{print $2}')
          echo "current_tag=$CURRENT_TAG" >> $GITHUB_OUTPUT
          echo "🔍 Current tag: $CURRENT_TAG"
          echo "🔍 Target tag: ${{ inputs.image_tag }}"
          
      - name: Update manifest
        working-directory: cloud-repo
        run: |
          if [ "${{ steps.check-tag.outputs.current_tag }}" = "${{ inputs.image_tag }}" ]; then
            echo "⚠️ Image tag is already ${{ inputs.image_tag }}. Forcing update..."
          fi
          sed -i "s/tag: .*/tag: ${{ inputs.image_tag }}/" k8s-argocd-helm/apps/${{ inputs.service }}/values.yaml
          
      - name: Commit and push
        working-directory: cloud-repo
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add k8s-argocd-helm/apps/${{ inputs.service }}/values.yaml
          
          if git diff --staged --quiet; then
            echo "⚠️ No changes to commit. Image tag might be the same."
            echo "🔄 Triggering ArgoCD sync anyway..."
          else
            git commit -m "Deploy ${{ inputs.service }} with image ${{ inputs.image_tag }}"
            git push
            echo "✅ Manifest updated and pushed"
          fi
          
      - name: Notify deployment
        run: |
          CURRENT_TAG="${{ steps.check-tag.outputs.current_tag }}"
          if [ "$CURRENT_TAG" = "${{ inputs.image_tag }}" ]; then
            MESSAGE="🔄 [수동 배포] **${{ inputs.service }}** 재배포\\n> 이미지: ${{ inputs.image_tag }} (동일)\\n> 브랜치: ${{ inputs.target_branch }}\\n> ArgoCD 수동 동기화 필요"
          else
            MESSAGE="🚀 [수동 배포] **${{ inputs.service }}**\\n> 이전: $CURRENT_TAG\\n> 이후: ${{ inputs.image_tag }}\\n> 브랜치: ${{ inputs.target_branch }}\\n> ArgoCD 동기화 중..."
          fi
          
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"content\": \"$MESSAGE\"}" \
               ${{ secrets.DISCORD_WEBHOOK_CICD_URL }}