name: Rollback BE Deploy

on:
  workflow_call:
    inputs:
      environment: # 값: "production" 또는 "stage"
        description: "대상 환경"
        required: true
        type: string

jobs:
  rollback:
    runs-on: ubuntu-latest

    steps:
      - name: Set environment variables
        run: |
          echo "ENVIRONMENT=${{ inputs.environment }}" >> $GITHUB_ENV
          echo "HOST=${{ inputs.environment == 'production' && secrets.PROD_SERVER_HOST || secrets.STAGING_SERVER_HOST }}" >> $GITHUB_ENV

      - name: Authenticate to GCP
        if: ${{ inputs.environment == 'production' }}
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Authenticate to GCP (Stage)
        if: ${{ inputs.environment != 'production' }}
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY_STAGING }}

      - name: SSH into server and rollback
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/deploy
            ./be_deploy.sh --rollback || exit 1

      - name: Health check with retries
        env:
          HOST: ${{ env.HOST }}
          ENVIRONMENT: ${{ env.ENVIRONMENT }}
        run: |
          echo "(Rollback) 🔍 헬스체크 시작: 최대 3회 시도합니다."

          if [[ "$ENVIRONMENT" == "production" ]]; then
            CHECK_URL="https://hertz-tuning.com/api/ping"
          else
            CHECK_URL="http://${HOST}:8080/api/ping"
          fi

          for i in {1..3}; do
            echo "⏱️ 시도 $i: $CHECK_URL"
            if curl -sf "$CHECK_URL"; then
              echo "(Rollback) ✅ 헬스체크 성공 🎉"
              exit 0
            else
              echo "::error::헬스체크 시도 $i 실패"
              sleep 15
            fi
          done

          echo "::error::(Rollback) ❌ 3회 헬스체크 실패 - 서버가 정상 기동되지 않음"
          exit 1

      - name: Send success notification
        if: success()
        run: |
          curl -H "Content-Type: application/json" \
            -X POST \
            -d "{\"content\": \"✅ [BE 롤백 완료] \`${{ inputs.environment }}\` 환경\"}" \
            ${{ secrets.DISCORD_WEBHOOK_CICD_URL }}

      - name: Send failure notification
        if: failure()
        run: |
          curl -H "Content-Type: application/json" \
            -X POST \
            -d "{\"content\": \"❌ [BE 롤백 실패] \`${{ inputs.environment }}\` 환경\"}" \
            ${{ secrets.DISCORD_WEBHOOK_CICD_URL }}
