apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: tuning-dev
  namespace: argocd
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    argocd.argoproj.io/sync-wave: "-10"
spec:
  description: Project tuning for DEV environment
  sourceRepos:
    - "*"
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
