apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: tuning-dev
  namespace: argocd
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: argocd
    meta.helm.sh/release-namespace: argocd
    argocd.argoproj.io/sync-wave: "-10"
spec:
  description: Project tuning for DEV environment
  sourceRepos:
    - "*"
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
